use_frameworks!

target 'DDScriptMessage_Example' do
  pod 'DDScriptMessage', :path => '../'

  target 'DDScriptMessage_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
