install! 'cocoapods', :deterministic_uuids => false

inhibit_all_warnings!
use_frameworks!
platform :ios, '8.0'

target 'DDScriptMessage_Example' do
    
    pod 'DDScriptMessage', :path => '../'

    target 'DDScriptMessage_Tests' do
        inherit! :search_paths
        pod 'Quick', '~> 1.2.0'
        pod 'Nimble', '~> 7.0.2'
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.1'
        end

    end
end
